
/*
 * 
 */

package com.sds.acube.app.mobile.ws.client.esbservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.8
 * Thu Jun 28 15:31:15 KST 2012
 * Generated source version: 2.2.8
 * 
 */


@WebServiceClient(name = "EsbAppServiceService", 
                  wsdlLocation = "http://70.7.32.236:8080/ep/app/esb/service/EsbAppService?wsdl",
                  targetNamespace = "http://impl.service.ws.app.acube.sds.com/") 
public class EsbAppServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.ws.app.acube.sds.com/", "EsbAppServiceService");
    public final static QName EsbAppServicePort = new QName("http://impl.service.ws.app.acube.sds.com/", "EsbAppServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://70.7.32.236:8080/ep/app/esb/service/EsbAppService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://70.7.32.236:8080/ep/app/esb/service/EsbAppService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EsbAppServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EsbAppServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsbAppServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IEsbAppService
     */
    @WebEndpoint(name = "EsbAppServicePort")
    public IEsbAppService getEsbAppServicePort() {
        return super.getPort(EsbAppServicePort, IEsbAppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEsbAppService
     */
    @WebEndpoint(name = "EsbAppServicePort")
    public IEsbAppService getEsbAppServicePort(WebServiceFeature... features) {
        return super.getPort(EsbAppServicePort, IEsbAppService.class, features);
    }

}
