
package com.sds.acube.app.mobile.ws.client.esbservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.8
 * Thu Jun 28 15:31:15 KST 2012
 * Generated source version: 2.2.8
 * 
 */

public final class IEsbAppService_EsbAppServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.ws.app.acube.sds.com/", "EsbAppServiceService");

    private IEsbAppService_EsbAppServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EsbAppServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EsbAppServiceService ss = new EsbAppServiceService(wsdlURL, SERVICE_NAME);
        IEsbAppService port = ss.getEsbAppServicePort();  
        
        {
        System.out.println("Invoking listAppDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _listAppDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppListVOs _listAppDoc__return = port.listAppDoc(_listAppDoc_arg0);
        System.out.println("listAppDoc.result=" + _listAppDoc__return);


        }
        {
        System.out.println("Invoking listBox...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _listBox_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppMenuVOs _listBox__return = port.listBox(_listBox_arg0);
        System.out.println("listBox.result=" + _listBox__return);


        }
        {
        System.out.println("Invoking listDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _listDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppListVOs _listDoc__return = port.listDoc(_listDoc_arg0);
        System.out.println("listDoc.result=" + _listDoc__return);


        }
        {
        System.out.println("Invoking selectDocInfo...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _selectDocInfo_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppDetailVO _selectDocInfo__return = port.selectDocInfo(_selectDocInfo_arg0);
        System.out.println("selectDocInfo.result=" + _selectDocInfo__return);


        }
        {
        System.out.println("Invoking countPortalDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _countPortalDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppItemCountVO _countPortalDoc__return = port.countPortalDoc(_countPortalDoc_arg0);
        System.out.println("countPortalDoc.result=" + _countPortalDoc__return);


        }
        {
        System.out.println("Invoking processDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppActionVO _processDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppResultVO _processDoc__return = port.processDoc(_processDoc_arg0);
        System.out.println("processDoc.result=" + _processDoc__return);


        }
        {
        System.out.println("Invoking countDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _countDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppItemCountVO _countDoc__return = port.countDoc(_countDoc_arg0);
        System.out.println("countDoc.result=" + _countDoc__return);


        }
        {
        System.out.println("Invoking selectDocInfoMobile...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _selectDocInfoMobile_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppDetailVO _selectDocInfoMobile__return = port.selectDocInfoMobile(_selectDocInfoMobile_arg0);
        System.out.println("selectDocInfoMobile.result=" + _selectDocInfoMobile__return);


        }
        {
        System.out.println("Invoking listMobileBox...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _listMobileBox_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppMenuVOs _listMobileBox__return = port.listMobileBox(_listMobileBox_arg0);
        System.out.println("listMobileBox.result=" + _listMobileBox__return);


        }
        {
        System.out.println("Invoking processAppDoc...");
        com.sds.acube.app.mobile.ws.client.esbservice.HeaderVO _processAppDoc_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.Files _processAppDoc_arg1 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppResultVO _processAppDoc__return = port.processAppDoc(_processAppDoc_arg0, _processAppDoc_arg1);
        System.out.println("processAppDoc.result=" + _processAppDoc__return);


        }
        {
        System.out.println("Invoking getAttachFile...");
        com.sds.acube.app.mobile.ws.client.esbservice.AppReqVO _getAttachFile_arg0 = null;
        com.sds.acube.app.mobile.ws.client.esbservice.AppAttachVO _getAttachFile__return = port.getAttachFile(_getAttachFile_arg0);
        System.out.println("getAttachFile.result=" + _getAttachFile__return);


        }

        System.exit(0);
    }

}
