package com.sds.acube.app.ws.client.bind;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-22T10:36:56.226+09:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "BindApproverInfoWCFImpl", 
                  wsdlLocation = "http://70.7.32.231/ep/app/mobile/ws/bindWCF/BindApproverInfoWCF.svc?wsdl",
                  targetNamespace = "http://bind.ws.mobile.app.acube.sds.com/") 
public class BindApproverInfoWCFImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bind.ws.mobile.app.acube.sds.com/", "BindApproverInfoWCFImpl");
    public final static QName BasicHttpBindingIBindApproverInfoWCF = new QName("http://bind.ws.mobile.app.acube.sds.com/", "BasicHttpBinding_IBindApproverInfoWCF");
    static {
        URL url = null;
        try {
            url = new URL("http://70.7.32.231/ep/app/mobile/ws/bindWCF/BindApproverInfoWCF.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BindApproverInfoWCFImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://70.7.32.231/ep/app/mobile/ws/bindWCF/BindApproverInfoWCF.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BindApproverInfoWCFImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BindApproverInfoWCFImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BindApproverInfoWCFImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BindApproverInfoWCFImpl(WebServiceFeature ... features) { 
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BindApproverInfoWCFImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BindApproverInfoWCFImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IBindApproverInfoWCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IBindApproverInfoWCF")
    public IBindApproverInfoWCF getBasicHttpBindingIBindApproverInfoWCF() {
        return super.getPort(BasicHttpBindingIBindApproverInfoWCF, IBindApproverInfoWCF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBindApproverInfoWCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IBindApproverInfoWCF")
    public IBindApproverInfoWCF getBasicHttpBindingIBindApproverInfoWCF(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIBindApproverInfoWCF, IBindApproverInfoWCF.class, features);
    }

}
